/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_blog_posts_is_faq_schema = pgEnum('enum_blog_posts_is_faq_schema', ['yes', 'no'])
export const enum_blog_posts_is_video_object_schema = pgEnum(
  'enum_blog_posts_is_video_object_schema',
  ['yes', 'no'],
)
export const enum_blog_posts_is_how_to_schema = pgEnum('enum_blog_posts_is_how_to_schema', [
  'yes',
  'no',
])
export const enum_blog_posts_is_item_list_schema = pgEnum('enum_blog_posts_is_item_list_schema', [
  'yes',
  'no',
])
export const enum_blog_posts_status = pgEnum('enum_blog_posts_status', ['draft', 'published'])
export const enum__blog_posts_v_version_is_faq_schema = pgEnum(
  'enum__blog_posts_v_version_is_faq_schema',
  ['yes', 'no'],
)
export const enum__blog_posts_v_version_is_video_object_schema = pgEnum(
  'enum__blog_posts_v_version_is_video_object_schema',
  ['yes', 'no'],
)
export const enum__blog_posts_v_version_is_how_to_schema = pgEnum(
  'enum__blog_posts_v_version_is_how_to_schema',
  ['yes', 'no'],
)
export const enum__blog_posts_v_version_is_item_list_schema = pgEnum(
  'enum__blog_posts_v_version_is_item_list_schema',
  ['yes', 'no'],
)
export const enum__blog_posts_v_version_status = pgEnum('enum__blog_posts_v_version_status', [
  'draft',
  'published',
])
export const enum_categories_status = pgEnum('enum_categories_status', ['draft', 'published'])
export const enum__categories_v_version_status = pgEnum('enum__categories_v_version_status', [
  'draft',
  'published',
])
export const enum_tags_status = pgEnum('enum_tags_status', ['draft', 'published'])
export const enum__tags_v_version_status = pgEnum('enum__tags_v_version_status', [
  'draft',
  'published',
])
export const enum_countries_status = pgEnum('enum_countries_status', ['draft', 'published'])
export const enum__countries_v_version_status = pgEnum('enum__countries_v_version_status', [
  'draft',
  'published',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    prefix: varchar('prefix').default('blogassets/local-uploads/'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const blog_posts_faq_items = pgTable(
  'blog_posts_faq_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    question: varchar('question'),
    answerRichText: jsonb('answer_rich_text'),
  },
  (columns) => [
    index('blog_posts_faq_items_order_idx').on(columns._order),
    index('blog_posts_faq_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [blog_posts.id],
      name: 'blog_posts_faq_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const blog_posts = pgTable(
  'blog_posts',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    slug: varchar('slug'),
    mainImage: integer('main_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    category: integer('category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    countryTag: integer('country_tag_id').references(() => countries.id, {
      onDelete: 'set null',
    }),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }),
    webflowlastPublished: timestamp('webflowlast_published', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    readTime: varchar('read_time'),
    taglines: varchar('taglines'),
    postBody: jsonb('post_body'),
    tocBasedOn: varchar('toc_based_on'),
    featured: boolean('featured').default(false),
    video: varchar('video'),
    metaTitle: varchar('meta_title'),
    metaDescription: varchar('meta_description'),
    metaKeywords: varchar('meta_keywords'),
    isFaqSchema: enum_blog_posts_is_faq_schema('is_faq_schema'),
    isVideoObjectSchema: enum_blog_posts_is_video_object_schema('is_video_object_schema'),
    videoThumbnailUrl: varchar('video_thumbnail_url'),
    videoContentUrl: varchar('video_content_url'),
    videoEmbedUrl: varchar('video_embed_url'),
    videoPublishedDate: varchar('video_published_date'),
    videoDuration: varchar('video_duration'),
    isHowToSchema: enum_blog_posts_is_how_to_schema('is_how_to_schema'),
    scriptForHowToSchema: varchar('script_for_how_to_schema'),
    isItemListSchema: enum_blog_posts_is_item_list_schema('is_item_list_schema'),
    scriptForItemListSchema: varchar('script_for_item_list_schema'),
    webflowId: varchar('webflow_id'),
    isArchived: boolean('is_archived').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_blog_posts_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('blog_posts_slug_idx').on(columns.slug),
    index('blog_posts_main_image_idx').on(columns.mainImage),
    index('blog_posts_category_idx').on(columns.category),
    index('blog_posts_country_tag_idx').on(columns.countryTag),
    index('blog_posts_updated_at_idx').on(columns.updatedAt),
    index('blog_posts_created_at_idx').on(columns.createdAt),
    index('blog_posts__status_idx').on(columns._status),
  ],
)

export const blog_posts_rels = pgTable(
  'blog_posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagsID: integer('tags_id'),
  },
  (columns) => [
    index('blog_posts_rels_order_idx').on(columns.order),
    index('blog_posts_rels_parent_idx').on(columns.parent),
    index('blog_posts_rels_path_idx').on(columns.path),
    index('blog_posts_rels_tags_id_idx').on(columns.tagsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [blog_posts.id],
      name: 'blog_posts_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'blog_posts_rels_tags_fk',
    }).onDelete('cascade'),
  ],
)

export const _blog_posts_v_version_faq_items = pgTable(
  '_blog_posts_v_version_faq_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    question: varchar('question'),
    answerRichText: jsonb('answer_rich_text'),
    _uuid: varchar('_uuid'),
  },
  (columns) => [
    index('_blog_posts_v_version_faq_items_order_idx').on(columns._order),
    index('_blog_posts_v_version_faq_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_blog_posts_v.id],
      name: '_blog_posts_v_version_faq_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const _blog_posts_v = pgTable(
  '_blog_posts_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => blog_posts.id, {
      onDelete: 'set null',
    }),
    version_name: varchar('version_name'),
    version_slug: varchar('version_slug'),
    version_mainImage: integer('version_main_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_category: integer('version_category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    version_countryTag: integer('version_country_tag_id').references(() => countries.id, {
      onDelete: 'set null',
    }),
    version_date: timestamp('version_date', { mode: 'string', withTimezone: true, precision: 3 }),
    version_webflowlastPublished: timestamp('version_webflowlast_published', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_readTime: varchar('version_read_time'),
    version_taglines: varchar('version_taglines'),
    version_postBody: jsonb('version_post_body'),
    version_tocBasedOn: varchar('version_toc_based_on'),
    version_featured: boolean('version_featured').default(false),
    version_video: varchar('version_video'),
    version_metaTitle: varchar('version_meta_title'),
    version_metaDescription: varchar('version_meta_description'),
    version_metaKeywords: varchar('version_meta_keywords'),
    version_isFaqSchema: enum__blog_posts_v_version_is_faq_schema('version_is_faq_schema'),
    version_isVideoObjectSchema: enum__blog_posts_v_version_is_video_object_schema(
      'version_is_video_object_schema',
    ),
    version_videoThumbnailUrl: varchar('version_video_thumbnail_url'),
    version_videoContentUrl: varchar('version_video_content_url'),
    version_videoEmbedUrl: varchar('version_video_embed_url'),
    version_videoPublishedDate: varchar('version_video_published_date'),
    version_videoDuration: varchar('version_video_duration'),
    version_isHowToSchema: enum__blog_posts_v_version_is_how_to_schema('version_is_how_to_schema'),
    version_scriptForHowToSchema: varchar('version_script_for_how_to_schema'),
    version_isItemListSchema: enum__blog_posts_v_version_is_item_list_schema(
      'version_is_item_list_schema',
    ),
    version_scriptForItemListSchema: varchar('version_script_for_item_list_schema'),
    version_webflowId: varchar('version_webflow_id'),
    version_isArchived: boolean('version_is_archived').default(false),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__blog_posts_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_blog_posts_v_parent_idx').on(columns.parent),
    index('_blog_posts_v_version_version_slug_idx').on(columns.version_slug),
    index('_blog_posts_v_version_version_main_image_idx').on(columns.version_mainImage),
    index('_blog_posts_v_version_version_category_idx').on(columns.version_category),
    index('_blog_posts_v_version_version_country_tag_idx').on(columns.version_countryTag),
    index('_blog_posts_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_blog_posts_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_blog_posts_v_version_version__status_idx').on(columns.version__status),
    index('_blog_posts_v_created_at_idx').on(columns.createdAt),
    index('_blog_posts_v_updated_at_idx').on(columns.updatedAt),
    index('_blog_posts_v_latest_idx').on(columns.latest),
  ],
)

export const _blog_posts_v_rels = pgTable(
  '_blog_posts_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    tagsID: integer('tags_id'),
  },
  (columns) => [
    index('_blog_posts_v_rels_order_idx').on(columns.order),
    index('_blog_posts_v_rels_parent_idx').on(columns.parent),
    index('_blog_posts_v_rels_path_idx').on(columns.path),
    index('_blog_posts_v_rels_tags_id_idx').on(columns.tagsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_blog_posts_v.id],
      name: '_blog_posts_v_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: '_blog_posts_v_rels_tags_fk',
    }).onDelete('cascade'),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    slug: varchar('slug'),
    metaDescription: varchar('meta_description'),
    webflowId: varchar('webflow_id'),
    title: varchar('title'),
    categoriesTagline: varchar('categories_tagline'),
    thumbnail: integer('thumbnail_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    isArchived: boolean('is_archived').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_categories_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('categories_slug_idx').on(columns.slug),
    index('categories_thumbnail_idx').on(columns.thumbnail),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
    index('categories__status_idx').on(columns._status),
  ],
)

export const _categories_v = pgTable(
  '_categories_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    version_name: varchar('version_name'),
    version_slug: varchar('version_slug'),
    version_metaDescription: varchar('version_meta_description'),
    version_webflowId: varchar('version_webflow_id'),
    version_title: varchar('version_title'),
    version_categoriesTagline: varchar('version_categories_tagline'),
    version_thumbnail: integer('version_thumbnail_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_isArchived: boolean('version_is_archived').default(false),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__categories_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_categories_v_parent_idx').on(columns.parent),
    index('_categories_v_version_version_slug_idx').on(columns.version_slug),
    index('_categories_v_version_version_thumbnail_idx').on(columns.version_thumbnail),
    index('_categories_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_categories_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_categories_v_version_version__status_idx').on(columns.version__status),
    index('_categories_v_created_at_idx').on(columns.createdAt),
    index('_categories_v_updated_at_idx').on(columns.updatedAt),
    index('_categories_v_latest_idx').on(columns.latest),
  ],
)

export const tags = pgTable(
  'tags',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    slug: varchar('slug'),
    title: varchar('title'),
    metaDescription: varchar('meta_description'),
    webflowId: varchar('webflow_id'),
    isArchived: boolean('is_archived').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_tags_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('tags_slug_idx').on(columns.slug),
    index('tags_updated_at_idx').on(columns.updatedAt),
    index('tags_created_at_idx').on(columns.createdAt),
    index('tags__status_idx').on(columns._status),
  ],
)

export const _tags_v = pgTable(
  '_tags_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => tags.id, {
      onDelete: 'set null',
    }),
    version_name: varchar('version_name'),
    version_slug: varchar('version_slug'),
    version_title: varchar('version_title'),
    version_metaDescription: varchar('version_meta_description'),
    version_webflowId: varchar('version_webflow_id'),
    version_isArchived: boolean('version_is_archived').default(false),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__tags_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_tags_v_parent_idx').on(columns.parent),
    index('_tags_v_version_version_slug_idx').on(columns.version_slug),
    index('_tags_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_tags_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_tags_v_version_version__status_idx').on(columns.version__status),
    index('_tags_v_created_at_idx').on(columns.createdAt),
    index('_tags_v_updated_at_idx').on(columns.updatedAt),
    index('_tags_v_latest_idx').on(columns.latest),
  ],
)

export const countries = pgTable(
  'countries',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    slug: varchar('slug'),
    countryCode: varchar('country_code'),
    webflowId: varchar('webflow_id'),
    rankning: numeric('rankning'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    isArchived: boolean('is_archived').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_countries_status('_status').default('draft'),
  },
  (columns) => [
    uniqueIndex('countries_slug_idx').on(columns.slug),
    index('countries_logo_idx').on(columns.logo),
    index('countries_updated_at_idx').on(columns.updatedAt),
    index('countries_created_at_idx').on(columns.createdAt),
    index('countries__status_idx').on(columns._status),
  ],
)

export const _countries_v = pgTable(
  '_countries_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => countries.id, {
      onDelete: 'set null',
    }),
    version_name: varchar('version_name'),
    version_slug: varchar('version_slug'),
    version_countryCode: varchar('version_country_code'),
    version_webflowId: varchar('version_webflow_id'),
    version_rankning: numeric('version_rankning'),
    version_logo: integer('version_logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_isArchived: boolean('version_is_archived').default(false),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__countries_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
  },
  (columns) => [
    index('_countries_v_parent_idx').on(columns.parent),
    index('_countries_v_version_version_slug_idx').on(columns.version_slug),
    index('_countries_v_version_version_logo_idx').on(columns.version_logo),
    index('_countries_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_countries_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_countries_v_version_version__status_idx').on(columns.version__status),
    index('_countries_v_created_at_idx').on(columns.createdAt),
    index('_countries_v_updated_at_idx').on(columns.updatedAt),
    index('_countries_v_latest_idx').on(columns.latest),
  ],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    'blog-postsID': integer('blog_posts_id'),
    categoriesID: integer('categories_id'),
    tagsID: integer('tags_id'),
    countriesID: integer('countries_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_blog_posts_id_idx').on(columns['blog-postsID']),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_tags_id_idx').on(columns.tagsID),
    index('payload_locked_documents_rels_countries_id_idx').on(columns.countriesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['blog-postsID']],
      foreignColumns: [blog_posts.id],
      name: 'payload_locked_documents_rels_blog_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'payload_locked_documents_rels_tags_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['countriesID']],
      foreignColumns: [countries.id],
      name: 'payload_locked_documents_rels_countries_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_blog_posts_faq_items = relations(blog_posts_faq_items, ({ one }) => ({
  _parentID: one(blog_posts, {
    fields: [blog_posts_faq_items._parentID],
    references: [blog_posts.id],
    relationName: 'faqItems',
  }),
}))
export const relations_blog_posts_rels = relations(blog_posts_rels, ({ one }) => ({
  parent: one(blog_posts, {
    fields: [blog_posts_rels.parent],
    references: [blog_posts.id],
    relationName: '_rels',
  }),
  tagsID: one(tags, {
    fields: [blog_posts_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
}))
export const relations_blog_posts = relations(blog_posts, ({ one, many }) => ({
  mainImage: one(media, {
    fields: [blog_posts.mainImage],
    references: [media.id],
    relationName: 'mainImage',
  }),
  category: one(categories, {
    fields: [blog_posts.category],
    references: [categories.id],
    relationName: 'category',
  }),
  countryTag: one(countries, {
    fields: [blog_posts.countryTag],
    references: [countries.id],
    relationName: 'countryTag',
  }),
  faqItems: many(blog_posts_faq_items, {
    relationName: 'faqItems',
  }),
  _rels: many(blog_posts_rels, {
    relationName: '_rels',
  }),
}))
export const relations__blog_posts_v_version_faq_items = relations(
  _blog_posts_v_version_faq_items,
  ({ one }) => ({
    _parentID: one(_blog_posts_v, {
      fields: [_blog_posts_v_version_faq_items._parentID],
      references: [_blog_posts_v.id],
      relationName: 'version_faqItems',
    }),
  }),
)
export const relations__blog_posts_v_rels = relations(_blog_posts_v_rels, ({ one }) => ({
  parent: one(_blog_posts_v, {
    fields: [_blog_posts_v_rels.parent],
    references: [_blog_posts_v.id],
    relationName: '_rels',
  }),
  tagsID: one(tags, {
    fields: [_blog_posts_v_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
}))
export const relations__blog_posts_v = relations(_blog_posts_v, ({ one, many }) => ({
  parent: one(blog_posts, {
    fields: [_blog_posts_v.parent],
    references: [blog_posts.id],
    relationName: 'parent',
  }),
  version_mainImage: one(media, {
    fields: [_blog_posts_v.version_mainImage],
    references: [media.id],
    relationName: 'version_mainImage',
  }),
  version_category: one(categories, {
    fields: [_blog_posts_v.version_category],
    references: [categories.id],
    relationName: 'version_category',
  }),
  version_countryTag: one(countries, {
    fields: [_blog_posts_v.version_countryTag],
    references: [countries.id],
    relationName: 'version_countryTag',
  }),
  version_faqItems: many(_blog_posts_v_version_faq_items, {
    relationName: 'version_faqItems',
  }),
  _rels: many(_blog_posts_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_categories = relations(categories, ({ one }) => ({
  thumbnail: one(media, {
    fields: [categories.thumbnail],
    references: [media.id],
    relationName: 'thumbnail',
  }),
}))
export const relations__categories_v = relations(_categories_v, ({ one }) => ({
  parent: one(categories, {
    fields: [_categories_v.parent],
    references: [categories.id],
    relationName: 'parent',
  }),
  version_thumbnail: one(media, {
    fields: [_categories_v.version_thumbnail],
    references: [media.id],
    relationName: 'version_thumbnail',
  }),
}))
export const relations_tags = relations(tags, () => ({}))
export const relations__tags_v = relations(_tags_v, ({ one }) => ({
  parent: one(tags, {
    fields: [_tags_v.parent],
    references: [tags.id],
    relationName: 'parent',
  }),
}))
export const relations_countries = relations(countries, ({ one }) => ({
  logo: one(media, {
    fields: [countries.logo],
    references: [media.id],
    relationName: 'logo',
  }),
}))
export const relations__countries_v = relations(_countries_v, ({ one }) => ({
  parent: one(countries, {
    fields: [_countries_v.parent],
    references: [countries.id],
    relationName: 'parent',
  }),
  version_logo: one(media, {
    fields: [_countries_v.version_logo],
    references: [media.id],
    relationName: 'version_logo',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    'blog-postsID': one(blog_posts, {
      fields: [payload_locked_documents_rels['blog-postsID']],
      references: [blog_posts.id],
      relationName: 'blog-posts',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: 'tags',
    }),
    countriesID: one(countries, {
      fields: [payload_locked_documents_rels.countriesID],
      references: [countries.id],
      relationName: 'countries',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_blog_posts_is_faq_schema: typeof enum_blog_posts_is_faq_schema
  enum_blog_posts_is_video_object_schema: typeof enum_blog_posts_is_video_object_schema
  enum_blog_posts_is_how_to_schema: typeof enum_blog_posts_is_how_to_schema
  enum_blog_posts_is_item_list_schema: typeof enum_blog_posts_is_item_list_schema
  enum_blog_posts_status: typeof enum_blog_posts_status
  enum__blog_posts_v_version_is_faq_schema: typeof enum__blog_posts_v_version_is_faq_schema
  enum__blog_posts_v_version_is_video_object_schema: typeof enum__blog_posts_v_version_is_video_object_schema
  enum__blog_posts_v_version_is_how_to_schema: typeof enum__blog_posts_v_version_is_how_to_schema
  enum__blog_posts_v_version_is_item_list_schema: typeof enum__blog_posts_v_version_is_item_list_schema
  enum__blog_posts_v_version_status: typeof enum__blog_posts_v_version_status
  enum_categories_status: typeof enum_categories_status
  enum__categories_v_version_status: typeof enum__categories_v_version_status
  enum_tags_status: typeof enum_tags_status
  enum__tags_v_version_status: typeof enum__tags_v_version_status
  enum_countries_status: typeof enum_countries_status
  enum__countries_v_version_status: typeof enum__countries_v_version_status
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  blog_posts_faq_items: typeof blog_posts_faq_items
  blog_posts: typeof blog_posts
  blog_posts_rels: typeof blog_posts_rels
  _blog_posts_v_version_faq_items: typeof _blog_posts_v_version_faq_items
  _blog_posts_v: typeof _blog_posts_v
  _blog_posts_v_rels: typeof _blog_posts_v_rels
  categories: typeof categories
  _categories_v: typeof _categories_v
  tags: typeof tags
  _tags_v: typeof _tags_v
  countries: typeof countries
  _countries_v: typeof _countries_v
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_blog_posts_faq_items: typeof relations_blog_posts_faq_items
  relations_blog_posts_rels: typeof relations_blog_posts_rels
  relations_blog_posts: typeof relations_blog_posts
  relations__blog_posts_v_version_faq_items: typeof relations__blog_posts_v_version_faq_items
  relations__blog_posts_v_rels: typeof relations__blog_posts_v_rels
  relations__blog_posts_v: typeof relations__blog_posts_v
  relations_categories: typeof relations_categories
  relations__categories_v: typeof relations__categories_v
  relations_tags: typeof relations_tags
  relations__tags_v: typeof relations__tags_v
  relations_countries: typeof relations_countries
  relations__countries_v: typeof relations__countries_v
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
